logo: mysticPrg
title: mysticPrg's tech blog
description: >
  mysticPrg 의 개인 블로그
#permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mysticPrg.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: mysticPrg's tech blog
banner-desc: creative mind

# Author settings
author-pic: face.jpg # your photo
author-name: Hyeongu Hwang
about-author: 하고 싶은거 많고 돈도 많이 벌고 싶은, 꿈많은 개발자.
author-job: 현재 카카오 FE팀 재직중
author-nick-names: mysticPrg, copy.left, hank

email: mysticPrg@gmail.com
website: https://mysticPrg.github.io

# Social link
google_url:
twitter_url:
instagram_url:
pinterest_url:
dribbble_url:
facebook_url: https://www.facebook.com/mysticprg

# Disqus
discus_identifier: mysticPrg # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", ".idea"]
